# WEIGHING SCALE CONSTANTS
NUMBER_OF_READINGS = 6
CHANNEL = 'A'
GAIN = 128
SCALE = -21.053

# NFC READER CONSTANTS
NFC_PORT = '/dev/ttyACM0'

# PINS (BCM numbering)
CLOCK_PIN = 6
DATA_PIN = 5
REGISTRATION_BTN_PIN = 21
TARE_BTN_PIN = 26

#lcd
RS_PIN = 19
EN_PIN = 13
D4_PIN = 11
D5_PIN = 9
D6_PIN = 10
D7_PIN = 22